# Generated by Django 4.0.6 on 2022-12-07 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('text_message', models.TextField(default='', help_text='广告内容信息', verbose_name='广告信息')),
                ('id_is', models.TextField(default='', help_text='预留备用', verbose_name='预留')),
                ('user', models.ManyToManyField(related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='消息')),
            ],
            options={
                'verbose_name': '消息表',
                'verbose_name_plural': '消息表',
                'db_table': 'Message',
            },
        ),
    ]
