version: '3.7'

services:
  base:
    build:
      context: ../
      dockerfile: docker/base/Dockerfile
      args:
        - CONTAINER_HOMEWORK=${CONTAINER_HOMEWORK}
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
        - CONTAINER_USER=${CONTAINER_USER}
        - CONTAINER_GROUP=${CONTAINER_GROUP}
    image: ${COMPOSE_PROJECT_NAME}-base
    environment:
      - TZ=UTC+8

networks:
  game:
    driver: bridge

volumes:
  redis:
  mysql: